version: "3.8"
services: 
  frontend:
    container_name: logicTools
    build: .
    ports:
      - 3000:3000
  cf-tunnel:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=$CF_TUNNEL_TOKEN